import type React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "sonner";
import { SidebarWrapper } from "@/components/sidebar-wrapper";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Toaster />
      <SidebarProvider>
        <div className="flex min-h-screen w-full overflow-hidden">
          <SidebarWrapper />
          <div className="flex-1 flex flex-col w-full">
            <header className="h-14 border-b px-4 flex items-center">
              <h1 className="text-lg font-medium">Site Builder</h1>
            </header>
            {children}
          </div>
        </div>
      </SidebarProvider>
    </div>
  );
}
